name: website
description: "Static links project for Minh Le Quang's applications"
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'
 
dependencies:
  flutter:
    sdk: flutter 
  url_launcher: ^6.3.1
  go_router: ^15.1.2
  markdown_widget: ^2.3.2+8
  url_strategy: ^0.3.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  image_path: "assets/images/logo_dreamart.png"
  web:
    generate: true
    image_path: "assets/images/logo_dreamart.png"
    # background_color: "#hexcode"
    # theme_color: "#hexcode"


flutter:
  uses-material-design: true
  assets:
    - assets/images/ 